# OMERO single-node deployment
# which manages the iptables
# to open only necessary ports.

- hosts: firewalled
  roles:
    - role: openmicroscopy.postgresql
    - role: openmicroscopy.omero-server
    - role: openmicroscopy.omero-web
    - role: openmicroscopy.omero-web
    - role: geerlingguy.firewall

  vars:
    postgresql_users_databases:
    - user: omero
      password: omero
      databases: [omero]
    postgresql_version: "9.6"
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "4063"
      - "4064"
