# OMERO single-node deployment

- hosts: omero-allinone
  roles:
    - role: openmicroscopy.postgresql
    - role: openmicroscopy.omero-server
    - role: openmicroscopy.omero-web

  vars:
    postgresql_users_databases:
    - user: omero
      password: omero
      databases: [omero]
    postgresql_version: "9.6"
    ice_python_wheel: http://users.openmicroscopy.org.uk/~spli/centos-zeroc-ice-py/dist/zeroc_ice-3.6.3-cp27-cp27mu-linux_x86_64.whl
